In [41]:
import numpy as np

In [42]:
a=np.array([[1,32],[5,7]])

In [43]:
type(a)

numpy.ndarray

In [44]:
np.arange(1,7,1.5)

array([1. , 2.5, 4. , 5.5])

In [45]:
from numpy.random import default_rng
np.random.randint((4,6))

array([3, 3])

In [52]:
np.ones((4,6),dtype=np.int32)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [54]:
A = np.ones((2, 2))
A


array([[1., 1.],
       [1., 1.]])

In [55]:
B = np.eye(2, 2)
B

array([[1., 0.],
       [0., 1.]])

In [56]:
C = np.zeros((2, 2))
C

array([[0., 0.],
       [0., 0.]])

In [57]:
D = np.diag((-3, -4))
D

array([[-3,  0],
       [ 0, -4]])

In [66]:
a=np.block([[A,B],[C,D]])
print(a.shape)
a

(4, 4)


array([[ 1.,  1.,  1.,  0.],
       [ 1.,  1.,  0.,  1.],
       [ 0.,  0., -3.,  0.],
       [ 0.,  0.,  0., -4.]])

In [67]:
a=np.array([[A,B],[C,D]])

In [68]:
a

array([[[[ 1.,  1.],
         [ 1.,  1.]],

        [[ 1.,  0.],
         [ 0.,  1.]]],


       [[[ 0.,  0.],
         [ 0.,  0.]],

        [[-3.,  0.],
         [ 0., -4.]]]])

In [69]:
a.shape

(2, 2, 2, 2)

In [70]:
x = np.array([[1, 2], [3, 4], [5, 6]])
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [71]:
x.shape

(3, 2)

In [77]:
x.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
x.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

ValueError: cannot reshape array of size 6 into shape (4,1)

In [83]:
np.arange(35).reshape(-1,7)

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [84]:
import os

In [91]:
os.getcwd()

'C:\\Users\\aftha\\OneDrive\\Desktop'

In [90]:
os.chdir('C:/Users/aftha/OneDrive/Desktop')

In [2]:
import pandas as pd

In [84]:
df=pd.read_csv('C:\\Users\\aftha\\OneDrive\\Desktop\\dog_breeds.csv')
df1=df.copy()

In [26]:
df.loc[3:8,'Name':'max_weight_female']

Name  min_life_expectancy  max_life_expectancy  \
3          Great Dane                    7                   10   
4               Boxer                   10                   12   
5           Dalmatian                   11                   13   
6  Poodle (Miniature)                   10                   18   
7         Bullmastiff                    7                    9   
8              Beagle                   10                   15   

   max_height_male  max_height_female  max_weight_male  max_weight_female  
3             32.0               32.0            175.0              140.0  
4             25.0               25.0             80.0               65.0  
5             24.0               24.0             70.0               70.0  
6             15.0               15.0             15.0               15.0  
7             27.0               27.0            130.0              120.0  
8             16.0               15.0             20.0               30.0

In [29]:
df1=df.set_index('Name')

In [31]:
df1.loc['Boxer':'Beagle','max_height_male':'min_height_female']

max_height_male  max_height_female  max_weight_male  \
Name                                                                      
Boxer                          25.0               25.0             80.0   
Dalmatian                      24.0               24.0             70.0   
Poodle (Miniature)             15.0               15.0             15.0   
Bullmastiff                    27.0               27.0            130.0   
Beagle                         16.0               15.0             20.0   

                    max_weight_female  min_height_male  min_height_female  
Name                                                                       
Boxer                            65.0             23.0               23.0  
Dalmatian                        70.0             19.0               19.0  
Poodle (Miniature)               15.0             10.0               10.0  
Bullmastiff                     120.0             25.0               25.0  
Beagle                           30.0             14.0               13.0

In [24]:
df.iloc[3:8,4:9]

max_height_female  max_weight_male  max_weight_female  min_height_male  \
3               32.0            175.0              140.0             30.0   
4               25.0             80.0               65.0             23.0   
5               24.0             70.0               70.0             19.0   
6               15.0             15.0               15.0             10.0   
7               27.0            130.0              120.0             25.0   

   min_height_female  
3               30.0  
4               23.0  
5               19.0  
6               10.0  
7               25.0

In [10]:
df.columns

Index(['Name', 'min_life_expectancy', 'max_life_expectancy', 'max_height_male',
       'max_height_female', 'max_weight_male', 'max_weight_female',
       'min_height_male', 'min_height_female', 'min_weight_male',
       'min_weight_female', 'good_with_children', 'good_with_other_dogs',
       'shedding', 'grooming', 'drooling', 'coat_length',
       'good_with_strangers', 'playfulness', 'protectiveness', 'trainability',
       'energy', 'barking'],
      dtype='object')

In [45]:
df.groupby(['max_height_female','max_life_expectancy']).mean()

min_life_expectancy  max_height_male  \
max_height_female max_life_expectancy                                         
7.0               16                                  12.0              7.0   
8.0               15                                  11.0              8.0   
                  16                                  14.0              8.0   
9.0               14                                  12.0              9.0   
                  15                                  12.0              9.0   
...                                                    ...              ...   
29.0              13                                  11.0             29.0   
30.0              13                                  10.0             30.0   
31.0              14                                   9.0             33.0   
32.0              10                                   7.0             32.0   
                  12                                  10.0             32.0   

                                       max_weight_male  max_weight_female  \
max_height_female max_life_expectancy                                       
7.0               16                               7.0                7.0   
8.0               15                               7.0                7.0   
                  16                               6.0                6.0   
9.0               14                              14.0               14.0   
                  15                               8.8                8.8   
...                                                ...                ...   
29.0              13                             150.0              120.0   
30.0              13                              70.0               65.0   
31.0              14                             105.0               85.0   
32.0              10                             175.0              140.0   
                  12                             120.0               90.0   

                                       min_height_male  min_height_female  \
max_height_female max_life_expectancy                                       
7.0               16                               6.0                6.0   
8.0               15                               7.0                7.0   
                  16                               5.0                5.0   
9.0               14                               6.0                6.0   
                  15                               7.0                7.0   
...                                                ...                ...   
29.0              13                              29.0               29.0   
30.0              13                              28.0               28.0   
31.0              14                              30.0               27.0   
32.0              10                              30.0               30.0   
                  12                              27.0               27.0   

                                       min_weight_male  min_weight_female  \
max_height_female max_life_expectancy                                       
7.0               16                               3.0                3.0   
8.0               15                               7.0                7.0   
                  16                               4.0                4.0   
9.0               14                               7.0                7.0   
                  15                               6.6                6.6   
...                                                ...                ...   
29.0              13                             110.0               80.0   
30.0              13                              65.0               60.0   
31.0              14                              75.0               60.0   
32.0              10                             140.0              110.0   
                  12                             110.0               80.0   

     

In [51]:
df2=pd.read_json('C:\\Users\\aftha\\OneDrive\\Desktop\\iris.json')

In [52]:
df2[0:10]

sepalLength  sepalWidth  petalLength  petalWidth species
0          5.1         3.5          1.4         0.2  setosa
1          4.9         3.0          1.4         0.2  setosa
2          4.7         3.2          1.3         0.2  setosa
3          4.6         3.1          1.5         0.2  setosa
4          5.0         3.6          1.4         0.2  setosa
5          5.4         3.9          1.7         0.4  setosa
6          4.6         3.4          1.4         0.3  setosa
7          5.0         3.4          1.5         0.2  setosa
8          4.4         2.9          1.4         0.2  setosa
9          4.9         3.1          1.5         0.1  setosa

In [118]:
import math

In [56]:
df2.groupby('sepalLength')['petalLength'].mean().astype('int32')

sepalLength
4.3    1
4.4    1
4.5    1
4.6    1
4.7    1
4.8    1
4.9    2
5.0    1
5.1    1
5.2    2
5.3    1
5.4    2
5.5    3
5.6    4
5.7    3
5.8    4
5.9    4
6.0    4
6.1    4
6.2    4
6.3    5
6.4    5
6.5    5
6.6    4
6.7    5
6.8    5
6.9    5
7.0    4
7.1    5
7.2    5
7.3    6
7.4    6
7.6    6
7.7    6
7.9    6
Name: petalLength, dtype: int32

In [119]:
x = np.array([1,3,5,6])
mean_x = np.mean(x)

In [120]:
mean_x

3.75

In [34]:
a={'car':['city','BMW'],'brand':['honda','BMW'],'year':[2012,2023],'model':['s','A']}

In [35]:
pd.DataFrame(a)

car  brand  year model
0  city  honda  2012     s
1   BMW    BMW  2023     A

In [39]:
d=pd.DataFrame(np.array([[1,2,3],[4,5,6],[7,8,9]]),columns=['a','b','c'])

In [38]:
import numpy as np

In [40]:
d

a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [50]:
d.groupby('a')['b'].median()

a
1    2.0
4    5.0
7    8.0
Name: b, dtype: float64

In [70]:
df.describe(include='all')

Name  min_life_expectancy  max_life_expectancy  \
count                 97            97.000000            97.000000   
unique                97                  NaN                  NaN   
top     Golden Retriever                  NaN                  NaN   
freq                   1                  NaN                  NaN   
mean                 NaN            11.360825            14.000000   
std                  NaN             1.653189             1.870829   
min                  NaN             7.000000             9.000000   
25%                  NaN            10.000000            13.000000   
50%                  NaN            12.000000            14.000000   
75%                  NaN            12.000000            15.000000   
max                  NaN            15.000000            19.000000   

        max_height_male  max_height_female  max_weight_male  \
count         97.000000          97.000000        97.000000   
unique              NaN                NaN              NaN   
top                 NaN                NaN              NaN   
freq                NaN                NaN              NaN   
mean          20.561856          20.427835        60.890722   
std            6.949692           6.836251        43.281424   
min            7.000000           7.000000         6.000000   
25%           15.000000          15.000000        23.000000   
50%           22.000000          22.000000        60.000000   
75%           27.000000          27.000000        85.000000   
max           33.000000          32.000000       200.000000   

        max_weight_female  min_height_male  min_height_female  \
count           97.000000        97.000000          97.000000   
unique                NaN              NaN                NaN   
top                   NaN              NaN                NaN   
freq                  NaN              NaN                NaN   
mean            54.292784        18.164948          18.061856   
std             36.473518         6.747963           6.656473   
min              6.000000         5.000000           5.000000   
25%             22.000000        12.000000          12.000000   
50%             55.000000        19.000000          19.000000   
75%             71.000000        24.000000          24.000000   
max            200.000000        30.000000          30.000000   

        min_weight_male  ...   shedding   grooming   drooling  coat_length  \
count         97.000000  ...  97.000000  97.000000  97.000000    97.000000   
unique              NaN  ...        NaN        NaN        NaN          NaN   
top                 NaN  ...        NaN        NaN        NaN          NaN   
freq                NaN  ...        NaN        NaN        NaN          NaN   
mean          46.024742  ...   2.587629   2.154639   1.618557     1.020619   
std           34.927431  ...   0.921418   1.034209   0.983651     0.203069   
min            3.000000  ...   0.000000   0.000000   0.000000     0.000000   
25%           15.000000  ...   2.000000   1.000000   1.000000     1.000000   
50%           40.000000  ...   3.000000   2.000000   1.000000     1.000000   
75%           65.000000  ...   3.000000   3.000000   2.000000     1.000000   
max          150.000000  ...   5.000000   5.000000   5.000000     2.000000   

        good_with_strangers  playfulness  protectiveness  trainability  \
count             97.000000    97.000000       97.000000     97.000000   
unique                  NaN          NaN             NaN           NaN   
top                     NaN          NaN             NaN           NaN   
freq                    NaN          NaN             NaN           NaN   
mean               3.402062     3.608247        3.659794      3.804124   
std                1.114860     0.984851        1.162671      0.975098   
min                0.000000     0.000000        0.000000      0.000000   
25%                3.000000     3.000000        3.000000      3.000000   
50%                3.000000     4.0000

In [71]:
df.describe()

min_life_expectancy  max_life_expectancy  max_height_male  \
count            97.000000            97.000000        97.000000   
mean             11.360825            14.000000        20.561856   
std               1.653189             1.870829         6.949692   
min               7.000000             9.000000         7.000000   
25%              10.000000            13.000000        15.000000   
50%              12.000000            14.000000        22.000000   
75%              12.000000            15.000000        27.000000   
max              15.000000            19.000000        33.000000   

       max_height_female  max_weight_male  max_weight_female  min_height_male  \
count          97.000000        97.000000          97.000000        97.000000   
mean           20.427835        60.890722          54.292784        18.164948   
std             6.836251        43.281424          36.473518         6.747963   
min             7.000000         6.000000           6.000000         5.000000   
25%            15.000000        23.000000          22.000000        12.000000   
50%            22.000000        60.000000          55.000000        19.000000   
75%            27.000000        85.000000          71.000000        24.000000   
max            32.000000       200.000000         200.000000        30.000000   

       min_height_female  min_weight_male  min_weight_female  ...   shedding  \
count          97.000000        97.000000          97.000000  ...  97.000000   
mean           18.061856        46.024742          40.076289  ...   2.587629   
std             6.656473        34.927431          28.510622  ...   0.921418   
min             5.000000         3.000000           3.000000  ...   0.000000   
25%            12.000000        15.000000          15.000000  ...   2.000000   
50%            19.000000        40.000000          35.000000  ...   3.000000   
75%            24.000000        65.000000          57.000000  ...   3.000000   
max            30.000000       150.000000         150.000000  ...   5.000000   

        grooming   drooling  coat_length  good_with_strangers  playfulness  \
count  97.000000  97.000000    97.000000            97.000000    97.000000   
mean    2.154639   1.618557     1.020619             3.402062     3.608247   
std     1.034209   0.983651     0.203069             1.114860     0.984851   
min     0.000000   0.000000     0.000000             0.000000     0.000000   
25%     1.000000   1.000000     1.000000             3.000000     3.000000   
50%     2.000000   1.000000     1.000000             3.000000     4.000000   
75%     3.000000   2.000000     1.000000             4.000000     4.000000   
max     5.000000   5.000000     2.000000             5.000000     5.000000   

       protectiveness  trainability     energy    barking  
count       97.000000     97.000000  97.000000  97.000000  
mean         3.659794      3.804124   3.680412   2.958763  
std          1.162671      0.975098   0.907680   1.257623  
min          0.000000      0.000000   0.000000   0.000000  
25%          3.000000      3.000000   3.000000   2.000000  
50%          4.000000      4.000000   4.000000   3.000000  
75%          5.000000      5.000000   4.000000   4.000000  
max          5.000000      5.000000   5.000000   5.000000  

[8 rows x 22 columns]

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Name                  97 non-null     object 
 1   min_life_expectancy   97 non-null     int64  
 2   max_life_expectancy   97 non-null     int64  
 3   max_height_male       97 non-null     float64
 4   max_height_female     97 non-null     float64
 5   max_weight_male       97 non-null     float64
 6   max_weight_female     97 non-null     float64
 7   min_height_male       97 non-null     float64
 8   min_height_female     97 non-null     float64
 9   min_weight_male       97 non-null     float64
 10  min_weight_female     97 non-null     float64
 11  good_with_children    97 non-null     int64  
 12  good_with_other_dogs  97 non-null     int64  
 13  shedding              97 non-null     int64  
 14  grooming              97 non-null     int64  
 15  drooling              97 

In [90]:
d=df[['max_weight_male']].astype('int32')

In [91]:
d

max_weight_male
0                75
1                32
2                80
3               175
4                80
..              ...
92               70
93               65
94               31
95                7
96               28

[97 rows x 1 columns]

In [98]:
df.drop(['max_weight_male'],axis=1,inplace=True)

In [103]:
df['max_weight_male']=d

In [104]:
df

Name  min_life_expectancy  max_life_expectancy  \
0                 Golden Retriever                   10                   12   
1                        Dachshund                   12                   16   
2               Labrador Retriever                   10                   12   
3                       Great Dane                    7                   10   
4                            Boxer                   10                   12   
..                             ...                  ...                  ...   
92  American Staffordshire Terrier                   12                   16   
93             Australian Shepherd                   12                   15   
94            Pembroke Welsh Corgi                   12                   13   
95               Yorkshire Terrier                   11                   15   
96                  French Bulldog                   10                   12   

    max_height_male  max_height_female  max_weight_female  min_height_male  \
0              24.0               24.0               65.0             23.0   
1               9.0                9.0               32.0              8.0   
2              24.5               24.5               70.0             22.5   
3              32.0               32.0              140.0             30.0   
4              25.0               25.0               65.0             23.0   
..              ...                ...                ...              ...   
92             19.0               19.0               55.0             18.0   
93             23.0               23.0               55.0             20.0   
94             12.0               12.0               28.0             10.0   
95              8.0                8.0                7.0              7.0   
96             13.0               13.0               26.0             11.0   

    min_height_female  min_weight_male  min_weight_female  ...  grooming  \
0                23.0             65.0               55.0  ...         2   
1                 8.0             16.0               16.0  ...         2   
2                22.5             65.0               55.0  ...         2   
3                30.0            140.0              110.0  ...         1   
4                23.0             65.0               50.0  ...         2   
..                ...              ...                ...  ...       ...   
92               18.0             55.0               40.0  ...         1   
93               20.0             50.0               40.0  ...         2   
94               10.0             24.0               24.0  ...         2   
95                7.0              7.0                7.0  ...         5   
96               11.0             20.0               18.0  ...         1   

    drooling  coat_length  good_with_strangers  playfulness  protectiveness  \
0          2            1                    5            4               3   
1          2            2                    4            4               4   
2          2            1                    5            5               3   
3          4            1                    3            4               5   
4          3            1                    4            4               4   
..       ...          ...                  ...          ...             ...   
92         1            1                    4            3               5   
93         1            1                    3            4               3   
94         1            1                    4            4               5   
95         1            1                    5            4               5   
96         3            1                    5            5               3   

    trainability  energy  barking  max_weight_male  
0              5       3        1               75  
1              4       3        5               32  
2              5       5        3               80  
3              3       4        3              175  
4    

In [108]:
df.iloc[:,5]=df['max_weight_male']

In [109]:
df

Name  min_life_expectancy  max_life_expectancy  \
0                 Golden Retriever                   10                   12   
1                        Dachshund                   12                   16   
2               Labrador Retriever                   10                   12   
3                       Great Dane                    7                   10   
4                            Boxer                   10                   12   
..                             ...                  ...                  ...   
92  American Staffordshire Terrier                   12                   16   
93             Australian Shepherd                   12                   15   
94            Pembroke Welsh Corgi                   12                   13   
95               Yorkshire Terrier                   11                   15   
96                  French Bulldog                   10                   12   

    max_height_male  max_height_female  max_weight_female  min_height_male  \
0              24.0               24.0                 75             23.0   
1               9.0                9.0                 32              8.0   
2              24.5               24.5                 80             22.5   
3              32.0               32.0                175             30.0   
4              25.0               25.0                 80             23.0   
..              ...                ...                ...              ...   
92             19.0               19.0                 70             18.0   
93             23.0               23.0                 65             20.0   
94             12.0               12.0                 31             10.0   
95              8.0                8.0                  7              7.0   
96             13.0               13.0                 28             11.0   

    min_height_female  min_weight_male  min_weight_female  ...  grooming  \
0                23.0             65.0               55.0  ...         2   
1                 8.0             16.0               16.0  ...         2   
2                22.5             65.0               55.0  ...         2   
3                30.0            140.0              110.0  ...         1   
4                23.0             65.0               50.0  ...         2   
..                ...              ...                ...  ...       ...   
92               18.0             55.0               40.0  ...         1   
93               20.0             50.0               40.0  ...         2   
94               10.0             24.0               24.0  ...         2   
95                7.0              7.0                7.0  ...         5   
96               11.0             20.0               18.0  ...         1   

    drooling  coat_length  good_with_strangers  playfulness  protectiveness  \
0          2            1                    5            4               3   
1          2            2                    4            4               4   
2          2            1                    5            5               3   
3          4            1                    3            4               5   
4          3            1                    4            4               4   
..       ...          ...                  ...          ...             ...   
92         1            1                    4            3               5   
93         1            1                    3            4               3   
94         1            1                    4            4               5   
95         1            1                    5            4               5   
96         3            1                    5            5               3   

    trainability  energy  barking  max_weight_male  
0              5       3        1               75  
1              4       3        5               32  
2              5       5        3               80  
3              3       4        3              175  
4    

In [112]:
df.isnull().sum()

Name                    0
min_life_expectancy     0
max_life_expectancy     0
max_height_male         0
max_height_female       0
max_weight_female       0
min_height_male         0
min_height_female       0
min_weight_male         0
min_weight_female       0
good_with_children      0
good_with_other_dogs    0
shedding                0
grooming                0
drooling                0
coat_length             0
good_with_strangers     0
playfulness             0
protectiveness          0
trainability            0
energy                  0
barking                 0
max_weight_male         0
dtype: int64